# This file was generated by GoReleaser. DO NOT EDIT.
cask "git-commit-summary" do
  version "0.43.2"

  on_macos do
    on_intel do
      sha256 "5cf06ae1a45d9623370adb972f0ca13fae7da540bbaf33fff92763dada261ed8"
      url "https://github.com/rm-hull/git-commit-summary/releases/download/v#{version}/git-commit-summary_#{version}_darwin_amd64.tar.gz",
        verified: "github.com/rm-hull/git-commit-summary"
    end
    on_arm do
      sha256 "431e1d83a04408b1b92a681b20206c1827fd8ec6bc4ab4b8a3073b31056893dc"
      url "https://github.com/rm-hull/git-commit-summary/releases/download/v#{version}/git-commit-summary_#{version}_darwin_arm64.tar.gz",
        verified: "github.com/rm-hull/git-commit-summary"
    end
  end

  on_linux do
    on_intel do
      sha256 "3c6fd29287ae33768faa3d5d3c449125a7bc950e305a15fa1848761194a6e811"
      url "https://github.com/rm-hull/git-commit-summary/releases/download/v#{version}/git-commit-summary_#{version}_linux_amd64.tar.gz",
        verified: "github.com/rm-hull/git-commit-summary"
    end
    on_arm do
      sha256 "e6397d5809a6a9640b000480d0990c5ca01c0ef3ea9b21004f08d394fe506ef7"
      url "https://github.com/rm-hull/git-commit-summary/releases/download/v#{version}/git-commit-summary_#{version}_linux_arm64.tar.gz",
        verified: "github.com/rm-hull/git-commit-summary"
    end
  end

  name "git-commit-summary"
  desc "Command-line tool to automatically generate a concise commit summary for staged changes in a git repo."
  homepage "https://github.com/rm-hull/git-commit-summary"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "git-commit-summary"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/git-commit-summary"]
    end
  end

  # No zap stanza required

end
