# This file was generated by GoReleaser. DO NOT EDIT.
cask "git-commit-summary" do
  version "0.36.10"

  on_macos do
    on_intel do
      sha256 "fabcb90d092a04a3e779a26161e5ab8845ce26ead50c5774cd6e7b4a8ffef2c2"
      url "https://github.com/rm-hull/git-commit-summary/releases/download/v#{version}/git-commit-summary_#{version}_darwin_amd64.tar.gz",
        verified: "github.com/rm-hull/git-commit-summary"
    end
    on_arm do
      sha256 "22e2fde4949f493fa5a66ff032307410fd0d833dd431b17f6e8357e190e5f9be"
      url "https://github.com/rm-hull/git-commit-summary/releases/download/v#{version}/git-commit-summary_#{version}_darwin_arm64.tar.gz",
        verified: "github.com/rm-hull/git-commit-summary"
    end
  end

  on_linux do
    on_intel do
      sha256 "7ba0fd125564d947674f311093b0e3f46a78b87dee2bc4d9273b076b3c74769b"
      url "https://github.com/rm-hull/git-commit-summary/releases/download/v#{version}/git-commit-summary_#{version}_linux_amd64.tar.gz",
        verified: "github.com/rm-hull/git-commit-summary"
    end
    on_arm do
      sha256 "9b8cd45712e5e8dc79dcecb20f0c06016f2942c6a53075120cc14ca9d5ac9454"
      url "https://github.com/rm-hull/git-commit-summary/releases/download/v#{version}/git-commit-summary_#{version}_linux_arm64.tar.gz",
        verified: "github.com/rm-hull/git-commit-summary"
    end
  end

  name "git-commit-summary"
  desc "Command-line tool to automatically generate a concise commit summary for staged changes in a git repo."
  homepage "https://github.com/rm-hull/git-commit-summary"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "git-commit-summary"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/git-commit-summary"]
    end
  end

  # No zap stanza required

end
