# This file was generated by GoReleaser. DO NOT EDIT.
cask "git-commit-summary" do
  version "0.45.2"

  on_macos do
    on_arm do
      sha256 "a5a8345ffa5a1eb8728cd8e95ba41ea9eb637dcb8102df6e01532cf3bebcdbad"
      url "https://github.com/rm-hull/git-commit-summary/releases/download/v#{version}/git-commit-summary_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "6be914b65664b922847279853ac3dd7b1fbe9c0f423eb08783db2e41d9f4370d"
      url "https://github.com/rm-hull/git-commit-summary/releases/download/v#{version}/git-commit-summary_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "a93a2e2cc5f53333eb4db687f84714bd21368d43c58e55c2256c13e91393b16b"
      url "https://github.com/rm-hull/git-commit-summary/releases/download/v#{version}/git-commit-summary_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "484f3b30a619cc9dddadfe7a811fea32a440ff67e5166f46fb1b9ea3268073be"
      url "https://github.com/rm-hull/git-commit-summary/releases/download/v#{version}/git-commit-summary_#{version}_linux_amd64.tar.gz"
    end
  end

  name "git-commit-summary"
  desc "Command-line tool to automatically generate a concise commit summary for staged changes in a git repo."
  homepage "https://github.com/rm-hull/git-commit-summary"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "git-commit-summary"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/git-commit-summary"]
    end
  end

  # No zap stanza required
end
